### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by kevingrondin** [dveldhoen/easyinvoice#42] opened 2021-09-13 18:34 UTC
When i create invoice he return this message

{
  error: 'Error',
  message: 'NoSuchKey: The specified key does not exist.',
  sentryId: 'eb96ab2ff2c5429e9b4ae11eb6911843'
}

**Comment by enriqueferrao** [comment] 2021-09-14 01:09
Same issue here.

Running the readme example works but it gives the above error if the logo or bg image url is changed

**Comment by enriqueferrao** [comment] 2021-09-14 03:38
@kevingrondin I think the issue is that for whatever reason it is now compulsory to put a image url for background unlike before where it was optional

I set the background to a white background image and the invoice got created

**Comment by kevingrondin** [comment] 2021-09-14 05:40
yes with a background it's work thanks

**Comment by dveldhoen** [comment] 2021-09-14 06:46
Thank you for bringing this bug to our attention. This bug introduced itself in an effort to speed up invoice generation time when not using a background, since it's a 'heavy' process. So that should not have given an error. The problem is now fixed and I would advice you to leave out the background parameter (when not required) to speed up the process. So better not use your blank background fix. The fix should be live in about 15 minutes from now.

**Closed by dveldhoen** 2021-09-14 06:46 UTC

**Comment by kevingrondin** [comment] 2021-09-14 14:39
> Thank you for bringing this bug to our attention. This bug introduced itself in an effort to speed up invoice generation time when not using a background, since it's a 'heavy' process. It should not have given an error. The problem is now fixed and I would advice you to leave out the background parameter (when not required) to speed up the process. So better not use your blank background fix. The fix should be live in about 15 minutes from now.

Great, in the catch of createinvoice I will try a retry by adding in the payload the background, just in case.

**Comment by kevingrondin** [comment] 2022-04-21 07:58
I open this issue
