### ISSUE TITLE
Importing issue

### ISSUE THREAD

**Issue by zub0r** [dveldhoen/easyinvoice#57] opened 2022-03-29 15:13 UTC
Hi, thanks for a great package!

I'm having issues importing it in nestjs (typescript):

```
node_modules/.pnpm/easyinvoice@2.3.0_pdfjs-dist@2.13.216/node_modules/easyinvoice/index.d.ts:90:5 - error TS2666: Exports and export assignments are not permitted in module augmentations.

export = easyinvoice
```

Neither of these imports worked:
`import { createInvoice, InvoiceData } from 'easyinvoice';`
`import easyinvoice from 'easyinvoice';`

Could it be because I'm using newer version of pdfjs? The old one had conflicts with my other dependencies.
Any suggestions?

Thanks!

**Comment by dveldhoen** [comment] 2022-03-29 15:28
Hi,

Thanks! Always nice to hear.
I'm sorry to hear you are experiencing issues. We will try to reproduce and fix it.

It would help to know what combination of packages you are using. Would it be possible to send a copy of your package.json to us at info@easyinvoice.cloud? We will treat it with the highest privacy and use it only for bugfixing purposes, after which we will delete it.

Any other way to reproduce would also be fine. Please let me know.

**Comment by dveldhoen** [comment] 2022-04-21 08:04
Since we didn't get a reply, I will close this issue for now.

**Closed by dveldhoen** 2022-04-21 08:04 UTC
